import { VignetteSet } from "@/types/cfa";

export const CFA_VIGNETTES: VignetteSet[] = [
  // TOPIC 01: Quantitative Methods
  {
    id: "vignette-01-quant",
    topicId: "01",
    topicName: "Quantitative Methods",
    subReading: "Rates & Returns, TVM, and Hypothesis Testing",
    difficulty: "High Trap",
    vignetteStem: "An institutional asset management analyst is constructing benchmark return forecasts and evaluating candidate investment funds. The portfolio requires monthly compounding rate transformations, annuity-due retirement cash flow projections, and two-tailed hypothesis testing against a historical benchmark return of 7.5% per annum.",
    questions: [
      {
        id: 101,
        losCode: "LOS 1.b",
        stem: "A corporate bond offering quotes a stated nominal annual interest rate of 8.40% compounded monthly. What is the Effective Annual Rate (EAR) generated by this security?",
        options: {
          A: "8.400%",
          B: "8.731%",
          C: "8.765%"
        },
        correctOption: "B",
        algebraicSolution: "EAR = (1 + r_s / m)^m - 1 = (1 + 0.084 / 12)^12 - 1 = (1.007)^12 - 1 = 1.087311 - 1 = 8.731%.",
        calculatorKeystrokes: "[2nd][ICONV] -> NOM = 8.40 [ENTER] -> [↓][↓] -> C/Y = 12 [ENTER] -> [↑] -> [CPT] EFF => 8.731%",
        trapCategory: "Effective Annual Rate Compounding Periodicity",
        errorModeDefault: "PERIODICITY_MISMATCH",
        distractorAutopsy: {
          A: "Distractor A assumes no intra-year compounding (treating stated rate equal to effective rate).",
          B: "CORRECT: Accurately applies (1 + 0.084/12)^12 - 1 = 8.731%.",
          C: "Distractor C assumes daily continuous compounding e^0.084 - 1 = 8.765%, compounding too frequently."
        }
      },
      {
        id: 102,
        losCode: "LOS 2.d",
        stem: "An endowment fund commits to paying an immediate scholarship grant of $50,000 at the beginning of each year for the next 6 years (payments at t = 0, 1, 2, 3, 4, 5). If the annual discount rate is 6.50%, the present value of this annuity due is closest to:",
        options: {
          A: "$241,986",
          B: "$257,715",
          C: "$274,466"
        },
        correctOption: "B",
        algebraicSolution: "PV(Ordinary) = $50,000 * [(1 - (1.065)^-6) / 0.065] = $241,986.08. PV(Annuity Due) = PV(Ordinary) * (1 + 0.065) = $241,986.08 * 1.065 = $257,715.18.",
        calculatorKeystrokes: "[2nd][BGN][2nd][SET][2nd][QUIT] -> [N] = 6 -> [I/Y] = 6.50 -> [PMT] = 50000 -> [FV] = 0 -> [CPT][PV] => -257,715.18",
        trapCategory: "Annuity Due Mode Timing Trap ([BGN] vs [END])",
        errorModeDefault: "BA2_MODE",
        distractorAutopsy: {
          A: "Distractor A is the classic ordinary annuity value computed in [END] mode, omitting the (1 + r) immediate timing factor.",
          B: "CORRECT: Accurately calculates present value in [BGN] mode ($257,715).",
          C: "Distractor C multiplies by (1 + r)^2, over-adjusting the compounding periods."
        }
      },
      {
        id: 103,
        losCode: "LOS 4.d",
        stem: "An equity analyst estimates that there is a 30% prior probability of an economic recession. In a recession, Company X has an 80% probability of cutting its dividend; without a recession, the probability of a dividend cut is only 15%. If Company X cuts its dividend, what is the updated posterior probability P(Recession | Cut)?",
        options: {
          A: "59.5%",
          B: "69.6%",
          C: "80.0%"
        },
        correctOption: "B",
        algebraicSolution: "Total P(Cut) = (0.30 * 0.80) + (0.70 * 0.15) = 0.24 + 0.105 = 0.345. P(Recession | Cut) = (0.30 * 0.80) / 0.345 = 0.24 / 0.345 = 69.57% ~ 69.6%.",
        calculatorKeystrokes: "[0.30] [\\times] [0.80] [=] 0.24 [STO] 1 -> [0.70] [\\times] [0.15] [+] [RCL] 1 [=] 0.345 [STO] 2 -> [RCL] 1 [\\div] [RCL] 2 [=] 0.6957",
        trapCategory: "Probability Trees and Conditional Expectations",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "Distractor A erroneously divides joint probability 0.24 by (0.24 + 0.163), misweighting prior probabilities.",
          B: "CORRECT: Applies Bayes' formula: P(A|B) = [P(B|A)*P(A)] / P(B) = 0.24 / 0.345 = 69.6%.",
          C: "Distractor C confuses P(Cut | Recession) = 80% with the posterior P(Recession | Cut)."
        }
      },
      {
        id: 104,
        losCode: "LOS 6.c",
        stem: "A sample of 25 monthly mutual fund returns yields a sample mean of 1.20% and sample standard deviation of 2.00%. The analyst tests H_0: μ = 0.50% against H_a: μ ≠ 0.50% at the 5% significance level (two-tailed critical t = 2.064 with 24 df). The calculated t-statistic and test conclusion are:",
        options: {
          A: "t = 1.75; Fail to reject H_0",
          B: "t = 2.064; Fail to reject H_0",
          C: "t = 1.75; Reject H_0"
        },
        correctOption: "A",
        algebraicSolution: "Standard Error = s / sqrt(n) = 2.00% / sqrt(25) = 2.00% / 5 = 0.40%. Test statistic t = (1.20% - 0.50%) / 0.40% = 0.70 / 0.40 = 1.75. Because |1.75| < 2.064, fail to reject H_0.",
        calculatorKeystrokes: "1.20 [-] 0.50 [=] 0.70 [\\div] (2.00 [\\div] [\\sqrt{25}]) [=] 1.75",
        trapCategory: "Hypothesis Testing & Parametric Tests",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "CORRECT: t = 1.75 is less than critical value 2.064; cannot reject null.",
          B: "Distractor B confuses the calculated test statistic with the critical cutoff.",
          C: "Distractor C makes the classic decision inversion, rejecting null when statistic is inside non-rejection zone."
        }
      },
      {
        id: 105,
        losCode: "LOS 7.c",
        stem: "In a simple linear regression of asset return on the market index, the Total Sum of Squares (SST) is 400 and the Sum of Squared Errors (SSE) is 140. The coefficient of determination (R-squared) is closest to:",
        options: {
          A: "0.350",
          B: "0.650",
          C: "0.725"
        },
        correctOption: "B",
        algebraicSolution: "Regression Sum of Squares (SSR) = SST - SSE = 400 - 140 = 260. R^2 = SSR / SST = 1 - (SSE / SST) = 1 - (140 / 400) = 1 - 0.35 = 0.65 (65%).",
        calculatorKeystrokes: "1 [-] (140 [\\div] 400) [=] 0.65",
        trapCategory: "Simple Linear Regression",
        errorModeDefault: "SIGN_INVERSION",
        distractorAutopsy: {
          A: "Distractor A calculates the unexplained variance ratio (SSE / SST = 140/400 = 0.35) instead of R-squared.",
          B: "CORRECT: R^2 = SSR / SST = 260 / 400 = 0.65.",
          C: "Distractor C computes sqrt(0.65) = 0.806 or misapplies degree of freedom adjustments."
        }
      }
    ]
  },

  // TOPIC 02: Economics
  {
    id: "vignette-02-econ",
    topicId: "02",
    topicName: "Economics",
    subReading: "Currency Cross-Rates, Elasticities, and Market Structure",
    difficulty: "Institutional",
    vignetteStem: "A macro strategy desk is analyzing FX arbitrage opportunities between London, Tokyo, and Zurich, while assessing market pricing power for an industrial manufacturer operating under monopolistic competition.",
    questions: [
      {
        id: 201,
        losCode: "LOS 12.c",
        stem: "A dealer quotes the following spot exchange rates:\n• USD/EUR: 1.1200 – 1.1205\n• USD/CHF: 0.9800 – 0.9805\nThe implied CHF/EUR bid cross-rate is closest to:",
        options: {
          A: "1.1423",
          B: "1.1428",
          C: "1.1434"
        },
        correctOption: "A",
        algebraicSolution: "CHF/EUR = (USD/EUR) / (USD/CHF). Bid(CHF/EUR) = Bid(USD/EUR) / Ask(USD/CHF) = 1.1200 / 0.9805 = 1.14227 ~ 1.1423.",
        calculatorKeystrokes: "1.1200 [\\div] 0.9805 [=] 1.14227",
        trapCategory: "Currency Exchange Rates & Cross-Rates",
        errorModeDefault: "PERIODICITY_MISMATCH",
        distractorAutopsy: {
          A: "CORRECT: Correctly matches Bid numerator to Ask denominator for cross-rate bid: 1.1200 / 0.9805 = 1.1423.",
          B: "Distractor B divides Bid by Bid (1.1200 / 0.9800 = 1.14285), ignoring bid-ask spread rules.",
          C: "Distractor C divides Ask by Ask (1.1205 / 0.9800 = 1.14336), yielding an ask rate rather than bid."
        }
      },
      {
        id: 202,
        losCode: "LOS 9.d",
        stem: "Which of the following characteristics is least likely to describe a firm operating in a monopolistically competitive industry in long-run equilibrium?",
        options: {
          A: "Price equals marginal cost (P = MC)",
          B: "Economic profit is equal to zero",
          C: "Demand curve facing the firm is downward sloping"
        },
        correctOption: "A",
        algebraicSolution: "In monopolistic competition, downward sloping demand means P > MR = MC. Thus P > MC in both short and long run (producing excess capacity). Freedom of entry drives economic profit to zero.",
        calculatorKeystrokes: "Conceptual rule: P = MC occurs ONLY in Perfect Competition.",
        trapCategory: "The Firm and Market Structures",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "CORRECT (Least Likely): P > MC in monopolistic competition due to product differentiation; P = MC only in perfect competition.",
          B: "Distractor B is true for monopolistic competition in long-run equilibrium due to low barriers to entry.",
          C: "Distractor C is true because product differentiation gives the firm a downward-sloping demand curve."
        }
      }
    ]
  },

  // TOPIC 03: Corporate Finance
  {
    id: "vignette-03-corpfin",
    topicId: "03",
    topicName: "Corporate Finance",
    subReading: "Cost of Capital (WACC) and Capital Allocation (NPV vs IRR)",
    difficulty: "High Trap",
    vignetteStem: "An industrial manufacturer with a 25% marginal corporate tax rate is reviewing its target capital structure. The firm can issue 10-year bonds at an 8.00% yield, preferred shares at 7.00%, and equity at 13.00% under CAPM. The target capital structure is 40% Debt, 10% Preferred, and 50% Common Equity.",
    questions: [
      {
        id: 301,
        losCode: "LOS 16.b",
        stem: "The firm's Weighted Average Cost of Capital (WACC) is closest to:",
        options: {
          A: "9.60%",
          B: "10.40%",
          C: "8.90%"
        },
        correctOption: "A",
        algebraicSolution: "After-tax cost of debt = 8.00% * (1 - 0.25) = 6.00%. WACC = (0.40 * 6.00%) + (0.10 * 7.00%) + (0.50 * 13.00%) = 2.40% + 0.70% + 6.50% = 9.60%.",
        calculatorKeystrokes: "0.40 [\\times] 8.00 [\\times] 0.75 [+] 0.10 [\\times] 7.00 [+] 0.50 [\\times] 13.00 [=] 9.60%",
        trapCategory: "WACC After-Tax Cost of Debt Trap",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "CORRECT: Properly incorporates the (1 - t) tax shield on debt: 0.40*(6.0%) + 0.10*(7.0%) + 0.50*(13.0%) = 9.60%.",
          B: "Distractor B fails to apply the tax shield to debt: 0.40*(8.0%) + 0.10*(7.0%) + 0.50*(13.0%) = 10.40%.",
          C: "Distractor C erroneously applies the (1 - t) tax shield to preferred stock dividends as well."
        }
      },
      {
        id: 302,
        losCode: "LOS 14.b",
        stem: "When evaluating two mutually exclusive projects of differing scales with positive NPVs, the CFO observes that Project A has NPV = $5.2M and IRR = 18%, while Project B has NPV = $7.1M and IRR = 14%. Assuming a cost of capital of 10%, the firm should:",
        options: {
          A: "Accept Project A because it provides a higher internal rate of return (18%)",
          B: "Accept Project B because it maximizes total shareholder dollar wealth ($7.1M)",
          C: "Accept both projects because both internal rates of return exceed the hurdle rate"
        },
        correctOption: "B",
        algebraicSolution: "For mutually exclusive projects, the NPV rule always dominates because it assumes reinvestment at the opportunity cost of capital (10%) and directly maximizes shareholder wealth. Accept Project B ($7.1M NPV).",
        calculatorKeystrokes: "Decision Rule: NPV dominates IRR for mutually exclusive projects.",
        trapCategory: "Capital Investments & Capital Allocation",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "Distractor A falls for the IRR ranking trap; IRR assumes unrealistic reinvestment at 18% and ignores project scale.",
          B: "CORRECT: For mutually exclusive projects, always maximize NPV ($7.1M > $5.2M).",
          C: "Distractor C ignores the condition that projects are mutually exclusive (cannot accept both)."
        }
      }
    ]
  },

  // TOPIC 04: Financial Statement Analysis
  {
    id: "vignette-04-fsa",
    topicId: "04",
    topicName: "Financial Statement Analysis",
    subReading: "Inventories, LIFO/FIFO Adjustments, and Lease Accounting",
    difficulty: "High Trap",
    vignetteStem: "Apex Heavy Industrial Corp reports under US GAAP using LIFO inventory valuation in an inflationary environment. For 2025, Apex reports LIFO COGS of $4,200,000, Beginning LIFO Reserve of $350,000, and Ending LIFO Reserve of $520,000. Marginal tax rate is 30%.",
    questions: [
      {
        id: 401,
        losCode: "LOS 18.c",
        stem: "If Apex had reported under FIFO, its 2025 Cost of Goods Sold (COGS) would be closest to:",
        options: {
          A: "$4,030,000",
          B: "$4,370,000",
          C: "$3,680,000"
        },
        correctOption: "A",
        algebraicSolution: "ΔLIFO Reserve = $520,000 - $350,000 = $170,000. COGS(FIFO) = COGS(LIFO) - ΔLIFO Reserve = $4,200,000 - $170,000 = $4,030,000.",
        calculatorKeystrokes: "4200000 [-] (520000 [-] 350000) [=] 4,030,000",
        trapCategory: "LIFO Reserve Change Directional Sign",
        errorModeDefault: "SIGN_INVERSION",
        distractorAutopsy: {
          A: "CORRECT: In rising prices, FIFO uses cheaper earlier costs: COGS = $4,200,000 - $170,000 = $4,030,000.",
          B: "Distractor B adds the delta reserve instead of subtracting it ($4,200,000 + $170,000 = $4,370,000).",
          C: "Distractor C subtracts the entire ending LIFO reserve ($520,000) rather than the single-period delta."
        }
      },
      {
        id: 402,
        losCode: "LOS 18.e",
        stem: "The cumulative adjustment to Apex's ending Retained Earnings balance upon converting from LIFO to FIFO at year-end 2025 is closest to an increase of:",
        options: {
          A: "$119,000",
          B: "$364,000",
          C: "$520,000"
        },
        correctOption: "B",
        algebraicSolution: "Retained Earnings adjustment = Ending LIFO Reserve * (1 - Tax Rate) = $520,000 * (1 - 0.30) = $520,000 * 0.70 = $364,000 increase.",
        calculatorKeystrokes: "520000 [\\times] 0.70 [=] 364,000",
        trapCategory: "Cumulative vs. Single-Period Reserve Tax Adjustment",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "Distractor A multiplies single-period ΔReserve ($170,000) by (1 - t), which is the single-period net income change, not cumulative retained earnings.",
          B: "CORRECT: Balance sheet cumulative retained earnings adjustment = Ending Reserve * (1 - t) = $520,000 * 0.70 = $364,000.",
          C: "Distractor C uses the gross ending LIFO reserve ($520,000), forgetting the cumulative deferred tax liability deduction."
        }
      }
    ]
  },

  // TOPIC 05: Equities
  {
    id: "vignette-05-equity",
    topicId: "05",
    topicName: "Equities",
    subReading: "Dividend Discount Valuation & Relative Multiples",
    difficulty: "High Trap",
    vignetteStem: "An equity research analyst is valuing shares of Vantage Dynamics Corp. The firm just paid an annual dividend D_0 = $2.50 per share. Dividends are forecast to grow at 15% per year for 2 years (years 1 and 2), and 4.0% perpetually thereafter. Required return on equity is 9.0%.",
    questions: [
      {
        id: 501,
        losCode: "LOS 25.b",
        stem: "The terminal share price P_2 at the end of Year 2 is closest to:",
        options: {
          A: "$68.74",
          B: "$66.10",
          C: "$58.12"
        },
        correctOption: "A",
        algebraicSolution: "D_1 = $2.50 * 1.15 = $2.875. D_2 = $2.875 * 1.15 = $3.30625. D_3 = D_2 * 1.04 = $3.30625 * 1.04 = $3.4385. Terminal Price P_2 = D_3 / (r - g) = $3.4385 / (0.09 - 0.04) = $3.4385 / 0.05 = $68.77 ~ $68.74.",
        calculatorKeystrokes: "2.50 [\\times] 1.15 [\\times] 1.15 [\\times] 1.04 [\\div] 0.05 [=] 68.77",
        trapCategory: "Gordon Growth Numerator Timing ($D_n$ vs $D_{n+1}$)",
        errorModeDefault: "PERIODICITY_MISMATCH",
        distractorAutopsy: {
          A: "CORRECT: Accurately advances dividend to D_3 ($3.4385) before dividing by (r - g) = 0.05 => $68.77.",
          B: "Distractor B uses D_2 ($3.306) in the Gordon Growth numerator without advancing to D_3 ($3.306 / 0.05 = $66.12).",
          C: "Distractor C divides D_1 by (r - g), creating a premature terminal horizon."
        }
      },
      {
        id: 502,
        losCode: "LOS 22.c",
        stem: "An investor purchases 1,000 shares of stock on margin at $60.00 per share with an initial margin requirement of 50% and maintenance margin of 30%. At what stock price will the investor receive a margin call?",
        options: {
          A: "$42.86",
          B: "$36.00",
          C: "$45.00"
        },
        correctOption: "A",
        algebraicSolution: "Margin Call Price = P_0 * [(1 - IM) / (1 - MM)] = $60 * [(1 - 0.50) / (1 - 0.30)] = $60 * (0.50 / 0.70) = $42.857 ~ $42.86.",
        calculatorKeystrokes: "60 [\\times] 0.50 [\\div] 0.70 [=] 42.857",
        trapCategory: "Market Organization and Structure",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "CORRECT: Margin Call Price = $60 * (1 - 0.50) / (1 - 0.30) = $42.86.",
          B: "Distractor B computes $60 * (1 - 0.40) or subtracts margin percentages linearly.",
          C: "Distractor C computes $60 * (1 - 0.50 * 0.50) = $45.00, misrepresenting broker maintenance equity formulas."
        }
      }
    ]
  },

  // TOPIC 06: Fixed Income
  {
    id: "vignette-06-fixedinc",
    topicId: "06",
    topicName: "Fixed Income",
    subReading: "Bond Convexity, Duration, and Semiannual Valuation",
    difficulty: "Institutional",
    vignetteStem: "A fixed income portfolio manager holds a 10-year, 6.00% semiannual coupon bond trading at par ($1,000) with a yield to maturity of 6.00%. The bond has a Modified Duration of 7.40 years and an Annual Convexity of 68.0.",
    questions: [
      {
        id: 601,
        losCode: "LOS 30.e",
        stem: "If market benchmark yields increase instantaneously by 150 basis points (+1.50%), the estimated percentage change in the bond's price using both Modified Duration and Convexity is closest to:",
        options: {
          A: "-10.335%",
          B: "-11.100%",
          C: "-9.570%"
        },
        correctOption: "A",
        algebraicSolution: "Duration effect = -ModDur * Δy = -7.40 * (+0.015) = -0.1110 (-11.10%). Convexity effect = 0.5 * Convexity * (Δy)^2 = 0.5 * 68.0 * (0.015)^2 = 34.0 * 0.000225 = +0.00765 (+0.765%). Total %ΔP ≈ -11.10% + 0.765% = -10.335%.",
        calculatorKeystrokes: "[-] 7.40 [\\times] 0.015 [+] (0.5 [\\times] 68.0 [\\times] 0.015 [x^2]) [=] -0.10335 => -10.335%",
        trapCategory: "Omission of the 1/2 Convexity Scalar Factor",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "CORRECT: Accurately applies %ΔP = -ModDur*(Δy) + 0.5*Convexity*(Δy)^2 = -11.10% + 0.765% = -10.335%.",
          B: "Distractor B uses only the linear Modified Duration term (-11.10%), omitting the positive convexity cushion.",
          C: "Distractor C omits the 1/2 multiplier on convexity (-11.10% + 1.530% = -9.570%)."
        }
      },
      {
        id: 602,
        losCode: "LOS 28.c",
        stem: "A 5-year corporate bond pays a 7.00% annual coupon semiannually (3.50% per period) on $1,000 par. If the market requires an annual YTM of 8.00%, the bond's price is closest to:",
        options: {
          A: "$959.45",
          B: "$960.07",
          C: "$972.10"
        },
        correctOption: "A",
        algebraicSolution: "N = 5 * 2 = 10; I/Y = 8.00 / 2 = 4.00%; PMT = (0.07 * 1000) / 2 = 35.00; FV = 1000. CPT PV = -$959.45.",
        calculatorKeystrokes: "[2nd][CLR TVM] -> [10][N] -> [4][I/Y] -> [35][PMT] -> [1000][FV] -> [CPT][PV] => -959.45",
        trapCategory: "Bond Semiannual Yield Convention",
        errorModeDefault: "PERIODICITY_MISMATCH",
        distractorAutopsy: {
          A: "CORRECT: N=10, I/Y=4%, PMT=35, FV=1000 => PV = $959.45.",
          B: "Distractor B uses annual compounding N=5, I/Y=8%, PMT=70 => PV = $960.07.",
          C: "Distractor C inputs I/Y=8% without dividing by 2 while using N=10, severely over-discounting."
        }
      }
    ]
  },

  // TOPIC 07: Derivatives
  {
    id: "vignette-07-deriv",
    topicId: "07",
    topicName: "Derivatives",
    subReading: "Put-Call Parity and Forward Valuation",
    difficulty: "High Trap",
    vignetteStem: "A quantitative derivatives desk is executing arbitrage monitoring across European options and forwards on Titan Stock. Titan currently trades at $100.00. The 1-year European call with strike $100 trades at $8.50, and 1-year risk-free rate is 5.00% continuously compounded.",
    questions: [
      {
        id: 701,
        losCode: "LOS 34.c",
        stem: "According to Put-Call Parity, the no-arbitrage price of a 1-year European put option with a $100 strike is closest to:",
        options: {
          A: "$3.62",
          B: "$4.88",
          C: "$8.50"
        },
        correctOption: "A",
        algebraicSolution: "PV(X) = 100 * e^(-0.05*1) = 100 * 0.95123 = $95.12. Put-Call Parity: p_0 = c_0 + PV(X) - S_0 = $8.50 + $95.12 - $100.00 = $3.62.",
        calculatorKeystrokes: "8.50 [+] (100 [\\times] [e^{-0.05}]) [-] 100 [=] 3.62",
        trapCategory: "Put-Call Parity Directional Sign Trap",
        errorModeDefault: "SIGN_INVERSION",
        distractorAutopsy: {
          A: "CORRECT: p = c + PV(X) - S = 8.50 + 95.12 - 100.00 = $3.62.",
          B: "Distractor B uses discrete simple compounding 100 / 1.05 = 95.24 - 100 + 8.50 = $3.74 or inverts spot and strike signs.",
          C: "Distractor C assumes call price must equal put price for at-the-money options."
        }
      },
      {
        id: 702,
        losCode: "LOS 33.b",
        stem: "Which of the following positions replicates a synthetic long asset position using options and bonds?",
        options: {
          A: "Long Call + Short Put + Long Zero-Coupon Bond (PV of Strike)",
          B: "Long Call + Long Put + Short Zero-Coupon Bond",
          C: "Short Call + Long Put + Long Zero-Coupon Bond"
        },
        correctOption: "A",
        algebraicSolution: "From Put-Call Parity S_0 = c_0 - p_0 + PV(X). To replicate Long Stock: Long Call (+c) + Short Put (-p) + Lend PV(X) (+Bond).",
        calculatorKeystrokes: "Synthetic Stock = Long Call + Short Put + PV(X)",
        trapCategory: "Put-Call Parity Directional Sign Trap",
        errorModeDefault: "SIGN_INVERSION",
        distractorAutopsy: {
          A: "CORRECT: S_0 = c_0 - p_0 + PV(X) => Long Call + Short Put + Long Bond.",
          B: "Distractor B creates a straddle combined with debt borrowing.",
          C: "Distractor C creates a synthetic short stock position."
        }
      }
    ]
  },

  // TOPIC 08: Alternative Investments
  {
    id: "vignette-08-alts",
    topicId: "08",
    topicName: "Alternative Investments",
    subReading: "Hedge Fund Fees, High-Water Marks, and Real Estate Valuation",
    difficulty: "High Trap",
    vignetteStem: "A private wealth client invests $10,000,000 in a hedge fund with a '2 and 20' fee structure (2% management fee calculated on beginning-of-year assets, 20% incentive fee calculated net of management fees with a high-water mark of $10,000,000). At year-end, gross fund value increases to $12,500,000.",
    questions: [
      {
        id: 801,
        losCode: "LOS 38.c",
        stem: "The total fees (management fee + incentive fee) earned by the hedge fund manager in Year 1 are closest to:",
        options: {
          A: "$660,000",
          B: "$700,000",
          C: "$500,000"
        },
        correctOption: "A",
        algebraicSolution: "Management Fee = 2% * $10,000,000 = $200,000. Net gain for incentive fee = $12,500,000 - $200,000 - $10,000,000 = $2,300,000. Incentive Fee = 20% * $2,300,000 = $460,000. Total Fee = $200,000 + $460,000 = $660,000.",
        calculatorKeystrokes: "10000000 [\\times] 0.02 [=] 200000 -> (12500000 [-] 200000 [-] 10000000) [\\times] 0.20 [+] 200000 [=] 660,000",
        trapCategory: "Hedge Funds & Fee Calculations",
        errorModeDefault: "FORMULA_SCALAR",
        distractorAutopsy: {
          A: "CORRECT: Accurately deducts management fee before computing incentive fee: $200k + $460k = $660,000.",
          B: "Distractor B computes the incentive fee gross of management fees: 20% * $2,500,000 = $500,000 + $200,000 = $700,000.",
          C: "Distractor C calculates only the incentive fee ($500,000) without adding the management fee."
        }
      },
      {
        id: 802,
        losCode: "LOS 37.b",
        stem: "A commercial office building generates $1,800,000 in potential gross income, with 5% vacancy/credit loss and $610,000 in operating expenses (including property taxes and insurance, but excluding $300,000 in mortgage interest). If market capitalization rate is 6.50%, estimated value is closest to:",
        options: {
          A: "$16,923,077",
          B: "$12,307,692",
          C: "$18,307,692"
        },
        correctOption: "A",
        algebraicSolution: "Effective Gross Income = $1,800,000 * 0.95 = $1,710,000. Net Operating Income (NOI) = $1,710,000 - $610,000 = $1,100,000 (NOI strictly ignores mortgage interest). Property Value = NOI / Cap Rate = $1,100,000 / 0.065 = $16,923,077.",
        calculatorKeystrokes: "(1800000 [\\times] 0.95 [-] 610000) [\\div] 0.065 [=] 16,923,076.92",
        trapCategory: "Real Estate & Infrastructure",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "CORRECT: NOI = $1,710,000 - $610,000 = $1,100,000. Value = $1,100,000 / 0.065 = $16,923,077.",
          B: "Distractor B erroneously subtracts mortgage interest from NOI ($1,100,000 - $300,000 = $800,000 / 0.065 = $12,307,692).",
          C: "Distractor C forgets to deduct operating expenses from gross revenue."
        }
      }
    ]
  },

  // TOPIC 09: Portfolio Construction
  {
    id: "vignette-09-port",
    topicId: "09",
    topicName: "Portfolio Construction",
    subReading: "CAPM, Beta, Security Market Line, and Performance Ratios",
    difficulty: "High Trap",
    vignetteStem: "An institutional endowment has a risk-free rate R_f = 4.00% and expected market portfolio return E(R_m) = 10.00%. An equity fund manager analyzes Stock Delta, which has an expected return of 13.50% and standard deviation of 24.0%. Market standard deviation is 15.0%, and correlation between Stock Delta and the market is 0.75.",
    questions: [
      {
        id: 901,
        losCode: "LOS 41.c",
        stem: "The beta of Stock Delta and its CAPM required rate of return are closest to:",
        options: {
          A: "Beta = 1.20; Required Return = 11.20%",
          B: "Beta = 1.20; Required Return = 13.50%",
          C: "Beta = 0.47; Required Return = 6.82%"
        },
        correctOption: "A",
        algebraicSolution: "Beta = Correlation * (σ_asset / σ_market) = 0.75 * (24.0% / 15.0%) = 0.75 * 1.60 = 1.20. CAPM Required Return = R_f + Beta * [E(R_m) - R_f] = 4.0% + 1.20 * (10.0% - 4.0%) = 4.0% + 1.20 * (6.0%) = 4.0% + 7.20% = 11.20%.",
        calculatorKeystrokes: "0.75 [\\times] (24 [\\div] 15) [=] 1.20 -> 4 [+] 1.20 [\\times] 6 [=] 11.20%",
        trapCategory: "Beta Ratio Inversion (Market vs Asset Volatility)",
        errorModeDefault: "SIGN_INVERSION",
        distractorAutopsy: {
          A: "CORRECT: Beta = 0.75 * (24/15) = 1.20. Required Return = 4% + 1.20*(6%) = 11.20%.",
          B: "Distractor B confuses the forecast expected return (13.50%) with the CAPM required return.",
          C: "Distractor C inverts the standard deviation ratio (0.75 * 15/24 = 0.46875), resulting in a wrong beta."
        }
      },
      {
        id: 902,
        losCode: "LOS 41.d",
        stem: "Based on its expected return of 13.50% and required return of 11.20%, Stock Delta plots relative to the Security Market Line (SML) as:",
        options: {
          A: "Above the SML and is undervalued (generate buy recommendation)",
          B: "Above the SML and is overvalued (generate sell recommendation)",
          C: "Below the SML and is overvalued (generate sell recommendation)"
        },
        correctOption: "A",
        algebraicSolution: "Alpha = Expected Return - Required Return = 13.50% - 11.20% = +2.30% (Positive Alpha). An asset offering higher return than required for its beta plots ABOVE the SML and is undervalued.",
        calculatorKeystrokes: "13.50 [-] 11.20 [=] +2.30% (Undervalued / Buy)",
        trapCategory: "Underpriced vs Overpriced SML Plot Inversion",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "CORRECT: Expected Return > Required Return => Positive Alpha (+2.30%) => Plots Above SML => Undervalued.",
          B: "Distractor B correctly identifies that it plots above SML but makes the polarity inversion concluding it is overvalued.",
          C: "Distractor C assumes it plots below the SML."
        }
      }
    ]
  },

  // TOPIC 10: Ethics
  {
    id: "vignette-10-ethics",
    topicId: "10",
    topicName: "Ethics",
    subReading: "Soft Dollars, Independence & Objectivity, and GIPS Standards",
    difficulty: "High Trap",
    vignetteStem: "Sarah Jenkins, CFA, manages discretionary equity portfolios at Apex Wealth. A regional broker provides Apex with in-depth proprietary equity research models and proposes using soft dollar client commissions to purchase Bloomberg terminals for Apex's research analysts and fund travel expenses for Jenkins to attend an annual issuer due diligence symposium in Geneva.",
    questions: [
      {
        id: 1001,
        losCode: "LOS 44.c",
        stem: "Under Standard III(A) Loyalty, Prudence, and Care, which of the proposed expenditures is permissible using client soft dollar brokerage commissions?",
        options: {
          A: "Proprietary equity research models and Bloomberg research data feeds only",
          B: "Bloomberg research terminals and travel expenses to the Geneva symposium",
          C: "All proposed expenditures, provided full written disclosure is made to clients"
        },
        correctOption: "A",
        algebraicSolution: "Soft dollar commissions belong to the client. Under Standard III(A) and CFA Institute Soft Dollar Standards, commissions may ONLY be used to purchase research and brokerage services that directly aid the investment decision-making process for client accounts. Travel expenses and office administrative overhead are strictly prohibited.",
        calculatorKeystrokes: "Conceptual Rule: Soft dollars must directly benefit client investment decisions.",
        trapCategory: "Soft Dollar Beneficiary Distinction",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "CORRECT: Investment research models and data feeds directly benefit client decision-making.",
          B: "Distractor B fails to recognize that travel and lodging expenses cannot be paid with client soft dollars.",
          C: "Distractor C erroneously assumes client disclosure waives core fiduciary prohibitions on misappropriation of brokerage."
        }
      },
      {
        id: 1002,
        losCode: "LOS 45.b",
        stem: "Apex Asset Management claims compliance with the Global Investment Performance Standards (GIPS). An audit reveals that Apex excluded three unprofitable terminated institutional portfolios from its 5-year historical composite track record. Under GIPS rules, this practice:",
        options: {
          A: "Directly breaches GIPS provisions because composites must include all past fee-paying discretionary portfolios, including terminated accounts",
          B: "Is permissible under GIPS provided the portfolios were terminated due to client liquidation rather than manager underperformance",
          C: "Is permissible if the composite presentation clearly discloses the exclusion in a footnote"
        },
        correctOption: "A",
        algebraicSolution: "GIPS standards mandate that composites include all actual, fee-paying, discretionary portfolios managed to that strategy, including terminated accounts for the full duration of their existence to eliminate survivorship bias.",
        calculatorKeystrokes: "Conceptual Rule: GIPS requires inclusion of terminated accounts to prevent survivorship bias.",
        trapCategory: "GIPS Provisions & Composite Construction",
        errorModeDefault: "CONCEPTUAL_CONFUSION",
        distractorAutopsy: {
          A: "CORRECT: GIPS strictly requires inclusion of terminated accounts to eliminate survivorship bias.",
          B: "Distractor B invents an unapproved liquidation exemption.",
          C: "Distractor C assumes footnote disclosures can override fundamental GIPS calculation rules."
        }
      }
    ]
  }
];
